
CREATE TABLE STORE (
	ID_STORE INT NOT NULL,
	NAMES VARCHAR(100) NOT NULL,
	CONSTRAINT PK_STORE PRIMARY KEY (ID_STORE)
);
CREATE TABLE MESSURE (
	ID_MESSURE INT NOT NULL,
	NAMES VARCHAR(100) NOT NULL,
	CONSTRAINT PK_MESSURE PRIMARY KEY(ID_MESSURE) 
);
CREATE TABLE MATERIAL(
	ID_MATERIAL INT NOT NULL,
	NAMES VARCHAR(100) NOT NULL,
	ID_MESSURE INT NOT NULL,
	CONSTRAINT PK_MATERIAL PRIMARY KEY (ID_MATERIAL),
	CONSTRAINT FK_MATERIAL_MESSURE FOREIGN KEY (ID_MESSURE) REFERENCES MESSURE (ID_MESSURE) ON DELETE CASCADE
);
CREATE TABLE SURPLUS(
	ID_SURPLUS INT NOT NULL,
	ID_MATERIAL INT NOT NULL,
	ID_STORE INT NOT NULL,
	VOLUME NUMERIC (5.2) NOT NULL,
	CONSTRAINT PK_SURPLUS PRIMARY KEY (ID_SURPLUS),
	CONSTRAINT FK_SURPLUS_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE,
	CONSTRAINT FK_SURPLAC_STORE FOREIGN KEY (ID_STORE) REFERENCES STORE (ID_STORE) ON DELETE CASCADE
);
CREATE TABLE EMPLOYER(
	ID_EMPLOYER INT NOT NULL,
	SURNAME VARCHAR(100) NOT NULL,
	NAMES VARCHAR(100) NOT NULL,
	FATHER_NAME VARCHAR(100) NOT NULL,
	CONSTRAINT PK_EMPLOYER PRIMARY KEY (ID_EMPLOYER)
);

CREATE TABLE CATERER(
	ID_CATERER INT NOT NULL,
	NAMES VARCHAR (100) NOT NULL,
	ADDRESS VARCHAR (100) NOT NULL,
	PHONE INT NOT NULL,
	FAX INT NOT NULL,
	CONSTRAINT PK_CATERER PRIMARY KEY (ID_CATERER)
);
CREATE TABLE SECTIONN(
	ID_SECTIONN INT NOT NULL,
	NAMES VARCHAR (100) NOT NULL,
	ID_EMPLOYER INT NOT NULL,
	CONSTRAINT PK_SECTIONN PRIMARY KEY (ID_SECTIONN),
	CONSTRAINT FK_SECTIONN_EMPLOYER FOREIGN KEY (ID_EMPLOYER) REFERENCES EMPLOYER (ID_EMPLOYER) ON DELETE CASCADE
);
CREATE TABLE INPRICE(
	ID_INPRICE INT NOT NULL,
	ID_MATERIAL INT NOT NULL,
	PRICE_DATE DATE NOT NULL,
	PRICE NUMERIC (10,2) CHECK (PRICE >=0),
	CONSTRAINT PK_INPRICE PRIMARY KEY (ID_INPRICE),
	CONSTRAINT FK_INPRICE_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE
);
CREATE TABLE SUPPLY(
	ID_SUPPLY INT NOT NULL,
	ID_CATERER INT NOT NULL,
	ID_STORE INT NOT NULL,
	ID_MATERIAL INT NOT NULL,
	SUPPLY_DATE DATE NOT NULL,
	VOLUME INT NOT NULL,
	CONSTRAINT PK_SUPPLY PRIMARY KEY (ID_SUPPLY),
	CONSTRAINT FK_SUPPLY_CATERER FOREIGN KEY (ID_CATERER) REFERENCES CATERER (ID_CATERER) ON DELETE CASCADE,
	CONSTRAINT FK_SUPPLY_STORE FOREIGN KEY (ID_STORE) REFERENCES STORE (ID_STORE) ON DELETE CASCADE,
	CONSTRAINT FK_SUPPLY_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE
);
CREATE TABLE DELIVER(
	ID_DELIVER INT NOT NULL,
	ID_MATERIAL INT NOT NULL,
	ID_STORE INT NOT NULL,
	ID_SECTIONN INT NOT NULL,
	DELIVER_DATE DATE NOT NULL,
	CONSTRAINT PK_DELIVER PRIMARY KEY (ID_DELIVER),
	CONSTRAINT FK_DELIVER_STORE FOREIGN KEY (ID_STORE) REFERENCES STORE (ID_STORE) ON DELETE CASCADE,
	CONSTRAINT FK_DELIVER_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE,
	CONSTRAINT FK_DELIVER_SECTIONN FOREIGN KEY (ID_SECTIONN) REFERENCES SECTIONN (ID_SECTIONN) ON DELETE CASCADE
);


ALTER TABLE CATERER DROP COLUMN ADDRESS;
ALTER TABLE CATERER ADD URADRES VARCHAR(100) NOT NULL;
ALTER TABLE CATERER ADD FAKTADRES VARCHAR(100) NOT NULL;
ALTER TABLE CATERER ADD ELPOCH VARCHAR(100) NOT NULL;
CREATE TABLE GROUPP(
	ID_GROUPP INT NOT NULL,
	ID_MATERIAL INT NOT NULL,
	CONSTRAINT PK_GROUPP PRIMARY KEY(ID_GROUPP),
	CONSTRAINT FK_GROUPP_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE SET NULL
);
ALTER TABLE INPRICE DROP CONSTRAINT ID_INPRICE;  
ALTER TABLE INPRICE ADD CONSTRAINT PK_ID_MATERIAL PRIMARY KEY (ID_MATERIAL);
ALTER TABLE INPRICE ADD CONSTRAINT PK_PRICE_DATE PRIMARY KEY (PRICE_DATE);



/*
DROP TABLE SUPPLY;
DROP TABLE INPRICE;
DROP TABLE DELIVER;
DROP TABLE CATERER;
DROP TABLE SURPLUS;
DROP TABLE SECTIONN;
DROP TABLE STORE;
DROP TABLE GROUPP;
DROP TABLE MATERIAL;
DROP TABLE MESSURE;
DROP TABLE EMPLOYER;
*/
