 
CREATE TABLE STORE (
	ID_STORE SERIAL,
	NAMES VARCHAR(100) NOT NULL,
	CONSTRAINT PK_STORE PRIMARY KEY (ID_STORE)
);
CREATE TABLE MESSURE (
	ID_MESSURE  SERIAL,
	NAMES VARCHAR(100) NOT NULL,
	CONSTRAINT PK_MESSURE PRIMARY KEY(ID_MESSURE) 
);
CREATE TABLE MATERIAL(
	ID_MATERIAL SERIAL,
	NAMES VARCHAR(100) NOT NULL,
	ID_MESSURE SERIAL,
	CONSTRAINT PK_MATERIAL PRIMARY KEY (ID_MATERIAL),
	CONSTRAINT FK_MATERIAL_MESSURE FOREIGN KEY (ID_MESSURE) REFERENCES MESSURE (ID_MESSURE) ON DELETE CASCADE
);
CREATE TABLE SURPLUS(
	ID_SURPLUS SERIAL,
	ID_MATERIAL SERIAL,
	ID_STORE SERIAL,
	VOLUME NUMERIC (10,2) NOT NULL,
	CONSTRAINT PK_SURPLUS PRIMARY KEY (ID_SURPLUS),
	CONSTRAINT FK_SURPLUS_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE,
	CONSTRAINT FK_SURPLAC_STORE FOREIGN KEY (ID_STORE) REFERENCES STORE (ID_STORE) ON DELETE CASCADE
);
CREATE TABLE EMPLOYER(
	ID_EMPLOYER SERIAL,
	SEMPOL VARCHAR (100) NOT NULL,
	SURNAME VARCHAR(100) NOT NULL,
	NAMES VARCHAR(100) NOT NULL,
	POL VARCHAR(1) NOT NULL,
	FATHER_NAME VARCHAR(100) NOT NULL,
	DATAROJ DATE NOT NULL,
	CONSTRAINT PK_EMPLOYER PRIMARY KEY (ID_EMPLOYER)
);

CREATE TABLE CATERER(
	ID_CATERER SERIAL,
	NAMES VARCHAR (100) NOT NULL,
	ADDRESS VARCHAR (100) NOT NULL,
	PHONE INT NOT NULL,
	FAX INT NOT NULL,
	CONSTRAINT PK_CATERER PRIMARY KEY (ID_CATERER)
);

CREATE TABLE SECTIONN(
	ID_SECTIONN SERIAL,
	NAMES VARCHAR (100) NOT NULL,
	ID_EMPLOYER SERIAL,
	CONSTRAINT PK_SECTIONN PRIMARY KEY (ID_SECTIONN),
	CONSTRAINT FK_SECTIONN_EMPLOYER FOREIGN KEY (ID_EMPLOYER) REFERENCES EMPLOYER (ID_EMPLOYER) ON DELETE CASCADE
);
CREATE TABLE INPRICE(
	ID_INPRICE SERIAL,
	ID_MATERIAL SERIAL,
	PRICE_DATE DATE NOT NULL,
	PRICE NUMERIC (10,2) CHECK (PRICE >=0),
	CONSTRAINT PK_INPRICE PRIMARY KEY (ID_INPRICE),
	CONSTRAINT FK_INPRICE_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE
);
CREATE TABLE SUPPLY(
	ID_SUPPLY SERIAL,
	ID_CATERER SERIAL,
	ID_STORE SERIAL,
	ID_MATERIAL SERIAL,
	SUPPLY_DATE DATE NOT NULL,
	VOLUME INT NOT NULL,
	CONSTRAINT PK_SUPPLY PRIMARY KEY (ID_SUPPLY),
	CONSTRAINT FK_SUPPLY_CATERER FOREIGN KEY (ID_CATERER) REFERENCES CATERER (ID_CATERER) ON DELETE CASCADE,
	CONSTRAINT FK_SUPPLY_STORE FOREIGN KEY (ID_STORE) REFERENCES STORE (ID_STORE) ON DELETE CASCADE,
	CONSTRAINT FK_SUPPLY_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE
);
CREATE TABLE DELIVER(
	ID_DELIVER SERIAL,
	ID_MATERIAL SERIAL,
	ID_STORE SERIAL,
	ID_SECTIONN SERIAL,
	DELIVER_DATE DATE NOT NULL,
	CONSTRAINT PK_DELIVER PRIMARY KEY (ID_DELIVER),
	CONSTRAINT FK_DELIVER_STORE FOREIGN KEY (ID_STORE) REFERENCES STORE (ID_STORE) ON DELETE CASCADE,
	CONSTRAINT FK_DELIVER_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE,
	CONSTRAINT FK_DELIVER_SECTIONN FOREIGN KEY (ID_SECTIONN) REFERENCES SECTIONN (ID_SECTIONN) ON DELETE CASCADE
);


ALTER TABLE CATERER DROP COLUMN ADDRESS;
ALTER TABLE CATERER ADD URADRES VARCHAR(100) NOT NULL;
ALTER TABLE CATERER ADD FAKTADRES VARCHAR(100) NOT NULL;
ALTER TABLE CATERER ADD ELPOCH VARCHAR(100) NOT NULL;
CREATE TABLE GROUPP(
	ID_GROUPP SERIAL,
	ID_MATERIAL SERIAL,
	CONSTRAINT PK_GROUPP PRIMARY KEY(ID_GROUPP),
	CONSTRAINT FK_GROUPP_MATERIAL FOREIGN KEY (ID_MATERIAL) REFERENCES MATERIAL (ID_MATERIAL) ON DELETE CASCADE
);


INSERT INTO STORE (NAMES) VALUES ('QWER1');
INSERT INTO STORE (NAMES) VALUES ('QWER2');
INSERT INTO STORE (NAMES) VALUES ('QWER3');
INSERT INTO STORE (NAMES) VALUES ('QWER4');
INSERT INTO STORE (NAMES) VALUES ('QWER5');
INSERT INTO MESSURE (NAMES) VALUES ('KG');
INSERT INTO MESSURE (NAMES) VALUES ('GRAMM');
INSERT INTO MESSURE (NAMES) VALUES ('TON');
INSERT INTO MESSURE (NAMES) VALUES ('L');
INSERT INTO MESSURE (NAMES) VALUES ('CM');
INSERT INTO MATERIAL (NAMES) VALUES ('VODA');
INSERT INTO MATERIAL (NAMES) VALUES ('CVMETAL');
INSERT INTO MATERIAL (NAMES) VALUES ('DER');
INSERT INTO MATERIAL (NAMES) VALUES ('ZEM');
INSERT INTO MATERIAL (NAMES) VALUES ('TEMMETAL');
INSERT INTO SURPLUS (VOLUME) VALUES ('12.40');
INSERT INTO SURPLUS (VOLUME) VALUES ('48.50');
INSERT INTO SURPLUS (VOLUME) VALUES ('32.33');
INSERT INTO SURPLUS (VOLUME) VALUES ('25.12');
INSERT INTO SURPLUS (VOLUME) VALUES ('71.48');
INSERT INTO EMPLOYER (SURNAME,NAMES,FATHER_NAME,SEMPOL,DATAROJ,POL) VALUES ('QW','ER','TY','JENAT','15.5.2001','M');
INSERT INTO EMPLOYER (SURNAME,NAMES,FATHER_NAME,SEMPOL,DATAROJ,POL) VALUES ('QQ','EE','TT','NEJENAT','11.4.2002','J');
INSERT INTO EMPLOYER (SURNAME,NAMES,FATHER_NAME,SEMPOL,DATAROJ,POL) VALUES ('WW','RR','YY','NEJENAT','2.9.2000','M');
INSERT INTO EMPLOYER (SURNAME,NAMES,FATHER_NAME,SEMPOL,DATAROJ,POL) VALUES ('WQ','RE','YT','NEJENAT','25.10.1999','J');
INSERT INTO EMPLOYER (SURNAME,NAMES,FATHER_NAME,SEMPOL,DATAROJ,POL) VALUES ('QQQ','WWW','EEE','JENAT','20.12.1990','M');
INSERT INTO CATERER (NAMES,URADRES,FAKTADRES,ELPOCH,PHONE,FAX) VALUES ('ASDF','FDSA','FDSA','POIU','123456','654321');
INSERT INTO CATERER (NAMES,URADRES,FAKTADRES,ELPOCH,PHONE,FAX) VALUES ('ASGF','FDSCV','FDSCV','POI','1234584','654871');
INSERT INTO CATERER (NAMES,URADRES,FAKTADRES,ELPOCH,PHONE,FAX) VALUES ('AZDF','FCSA','FCSA','POSD','12396','6124321');
INSERT INTO CATERER (NAMES,URADRES,FAKTADRES,ELPOCH,PHONE,FAX) VALUES ('ASDG','FDM','FDM','DFHGF','123106','653021');
INSERT INTO CATERER (NAMES,URADRES,FAKTADRES,ELPOCH,PHONE,FAX) VALUES ('ASDF','FDKLJA','FDKLJA','VGTXB','156','963321');
INSERT INTO SECTIONN (NAMES) VALUES ('ZXER');
INSERT INTO SECTIONN (NAMES) VALUES ('ZXAS');
INSERT INTO SECTIONN (NAMES) VALUES ('ZXQW');
INSERT INTO SECTIONN (NAMES) VALUES ('ZXCV');
INSERT INTO SECTIONN (NAMES) VALUES ('ZXDF');
INSERT INTO INPRICE (PRICE_DATE,PRICE) VALUES ('30.11.2000','11');
INSERT INTO INPRICE (PRICE_DATE,PRICE) VALUES ('12.8.2010','10');
INSERT INTO INPRICE (PRICE_DATE,PRICE) VALUES ('21.1.2010','8');
INSERT INTO INPRICE (PRICE_DATE,PRICE) VALUES ('10.5.1999','6');
INSERT INTO INPRICE (PRICE_DATE,PRICE) VALUES ('15.7.2010','8');
INSERT INTO SUPPLY (SUPPLY_DATE,VOLUME) VALUES ('12.12.2010','12');
INSERT INTO SUPPLY (SUPPLY_DATE,VOLUME) VALUES ('11.11.2011','48');
INSERT INTO SUPPLY (SUPPLY_DATE,VOLUME) VALUES ('10.10.2010','32');
INSERT INTO SUPPLY (SUPPLY_DATE,VOLUME) VALUES ('9.9.1999','25');
INSERT INTO SUPPLY (SUPPLY_DATE,VOLUME) VALUES ('8.8.1998','71');
INSERT INTO DELIVER (DELIVER_DATE) VALUES ('1.1.2001');
INSERT INTO DELIVER (DELIVER_DATE) VALUES ('2.2.2002');
INSERT INTO DELIVER (DELIVER_DATE) VALUES ('3.3.2000');
INSERT INTO DELIVER (DELIVER_DATE) VALUES ('4.4.2010');
INSERT INTO DELIVER (DELIVER_DATE) VALUES ('5.5.2010');



DELETE FROM INPRICE WHERE PRICE_DATE < '31.12.2000'; /*8*/
DELETE FROM MESSURE WHERE NAMES LIKE '_'; /*9*/
DELETE FROM STORE  WHERE NAMES = 'QWER1';/*10*/
UPDATE EMPLOYER SET dataroj = '11.04.2000', sempol='JENAT' WHERE dataroj='11.04.2002' AND sempol='NEJENAT,';/*11*/
UPDATE CATERER SET PHONE = '1' WHERE PHONE='156';/*12*/
UPDATE INPRICE SET PRICE = PRICE*0.85 WHERE PRICE_DATE >='01.01.2010' AND PRICE_DATE<='31.12.2010';/*13*/




/*
DROP TABLE SUPPLY;
DROP TABLE INPRICE;
DROP TABLE DELIVER;
DROP TABLE CATERER;
DROP TABLE SURPLUS;
DROP TABLE SECTIONN;
DROP TABLE STORE;
DROP TABLE GROUPP;
DROP TABLE MATERIAL;
DROP TABLE MESSURE;
DROP TABLE EMPLOYER;
*/
